"use strict";
/* A small JSON-file store. Single admin, low volume — a database would be
   more machinery than this needs. Writes go to a temp file and are renamed,
   so an interrupted write cannot truncate the store. */

const fs = require("fs");
const path = require("path");
const { DATA, UPLOADS, SUBMISSIONS } = require("./paths");

function ensureDirs() {
  fs.mkdirSync(UPLOADS, { recursive: true, mode: 0o700 });
  fs.chmodSync(DATA, 0o700);
}

function readAll() {
  try {
    const raw = fs.readFileSync(SUBMISSIONS, "utf8");
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch (err) {
    if (err.code === "ENOENT") return [];
    throw err;
  }
}

let writeQueue = Promise.resolve();
function writeAll(list) {
  // serialise writes so two requests cannot interleave read-modify-write
  writeQueue = writeQueue.then(() => {
    const tmp = SUBMISSIONS + "." + process.pid + ".tmp";
    fs.writeFileSync(tmp, JSON.stringify(list, null, 2), { mode: 0o600 });
    fs.renameSync(tmp, SUBMISSIONS);
  });
  return writeQueue;
}

async function add(record) {
  const list = readAll();
  list.unshift(record);
  await writeAll(list);
  return record;
}

async function update(id, patch) {
  const list = readAll();
  const i = list.findIndex((r) => r.id === id);
  if (i === -1) return null;
  list[i] = Object.assign({}, list[i], patch);
  await writeAll(list);
  return list[i];
}

async function remove(id) {
  const list = readAll();
  const rec = list.find((r) => r.id === id);
  if (!rec) return null;
  await writeAll(list.filter((r) => r.id !== id));
  if (rec.file && rec.file.storedName) {
    // storedName is generated by us and validated here as a defence in depth:
    // it must be a bare filename, never a path.
    const safe = path.basename(rec.file.storedName);
    try { fs.unlinkSync(path.join(UPLOADS, safe)); } catch (_) { /* already gone */ }
  }
  return rec;
}

function get(id) {
  return readAll().find((r) => r.id === id) || null;
}

module.exports = { ensureDirs, readAll, get, add, update, remove };
